'use client';
import { useEffect, useState } from 'react';
import { Building2, ChevronRight, ClipboardList, MessageSquare, ShieldCheck } from 'lucide-react';
import FeedbackPanel from '../components/FeedbackPanel';
import type { Followup } from '../lib/feedback-contract';
import './team-control.css';
export default function TeamControl() {
 const [items, setItems] = useState<Followup[]>([]); const [selectedId, setSelectedId] = useState(''); const [tab, setTab] = useState('feedback'); const [error, setError] = useState('');
 useEffect(() => { document.title = 'Acompanhamentos | MM Team Control — Teste'; fetch('/api/acompanhamentos').then(async r => { const data = await r.json() as Followup[] & { message?: string }; if (!r.ok) throw new Error(data.message); setItems(data); setSelectedId(data[0]?.id || ''); }).catch(e => setError(e.message)); }, []);
 const current = items.find(a => a.id === selectedId);
 return <main className="team-control"><aside className="sidebar"><a className="brand" href="/"><span>MM</span><div>Team Control<small>360</small></div></a><div className="workspace-label">ÁREA DE TRABALHO</div><a className="side-item selected" href="/acompanhamentos"><ClipboardList size={18}/> Acompanhamentos</a><div className="sidebar-foot"><ShieldCheck size={17}/><span>Ambiente de teste<br/><small>Empresas fictícias</small></span></div></aside><div className="team-main"><header className="topbar"><strong>Acompanhamentos</strong><span className="test-badge">DEMONSTRAÇÃO</span><div className="avatar">MM</div></header><div className="team-content"><div className="breadcrumb">Área de trabalho <ChevronRight size={14}/> Acompanhamentos</div><div className="title-row"><div><span className="eyebrow">RELACIONAMENTO COM O CLIENTE</span><h1>Painel do acompanhamento</h1></div></div><section className="company-picker"><Building2 size={21}/><label htmlFor="company">Empresa / acompanhamento</label><select id="company" value={selectedId} onChange={e => setSelectedId(e.target.value)}>{items.map(item => <option key={item.id} value={item.id}>{item.company} — {item.title}</option>)}</select></section>{error && <p role="alert" className="error">{error}</p>}{!current && !error && <p>Carregando acompanhamentos…</p>}{current && <><section className="followup-summary"><div className="summary-icon"><Building2 size={25}/></div><div><p>{current.company}</p><h2>{current.title}</h2><div className="summary-meta"><span>Responsável: <strong>{current.responsible}</strong></span><span>Código: <strong>{current.id}</strong></span></div></div><span className="pill green">{current.status}</span></section><nav className="detail-tabs" aria-label="Seções do acompanhamento"><button aria-current={tab === 'info' ? 'page' : undefined} className={tab === 'info' ? 'active' : ''} onClick={() => setTab('info')}>Informações</button><button aria-current={tab === 'feedback' ? 'page' : undefined} className={tab === 'feedback' ? 'active' : ''} onClick={() => setTab('feedback')}><MessageSquare size={17}/> Feedback</button></nav>{tab === 'feedback' ? <FeedbackPanel key={current.id} acompanhamentoId={current.id}/> : <section className="feedback-panel"><h3>Informações do acompanhamento</h3><p>Cliente: {current.company}</p><p>Projeto: {current.title}</p><p>Responsável: {current.responsible}</p><p>Status: {current.status}</p></section>}</>}<footer className="demo-footer">MM Team Control 360 · Teste do fluxo de feedback</footer></div></div></main>;
}
