'use client';

import { FormEvent, useEffect, useRef, useState } from 'react';
import { ArrowRight, CheckCircle2, MessageCircle, MonitorCog, Presentation, Send } from 'lucide-react';

const WHATSAPP_URL = 'https://wa.me/5547996527106?text=Ol%C3%A1%2C%20gostaria%20de%20enviar%20meu%20feedback%20para%20a%20MM%20Softwares.';
const forms = {
  treinamento: { eyebrow: 'Treinamento e implantação', title: 'Conte como foi sua experiência', description: 'Avalie a clareza do treinamento, o acompanhamento da equipe e os pontos que podemos melhorar.', icon: Presentation },
  produtos: { eyebrow: 'Produtos MM Softwares', title: 'Avalie o SIWEB e/ou WMS', description: 'Compartilhe sua percepção sobre as soluções e atribua uma nota de 1 a 5 para sua experiência.', icon: MonitorCog },
} as const;
type FormKey = keyof typeof forms;

function Field({ label, name, paragraph = false, required = false }: { label: string; name: string; paragraph?: boolean; required?: boolean }) {
  const styles = 'w-full border border-borda-clara-2 bg-white px-4 text-[15px] text-grafite transition-all duration-300 placeholder:text-texto-suave-2 focus:border-verde focus:outline-none focus:ring-2 focus:ring-verde/15';
  return <label className="block"><span className="mb-2 block font-titulo text-sm font-semibold text-grafite">{label}{required && <span className="ml-1 text-verde">*</span>}</span>{paragraph ? <textarea name={name} required={required} rows={4} className={`${styles} resize-y py-3.5 leading-6`} placeholder="Escreva sua resposta" /> : <input name={name} required={required} className={`${styles} h-[52px]`} placeholder="Sua resposta" />}</label>;
}

function ContainerWireframe() {
  const longFace = { width: 446.4, height: 190.8, marginLeft: -223.2, marginTop: -95.4 };
  const sideFace = { width: 180, height: 190.8, marginLeft: -90, marginTop: -95.4 };
  return <div aria-hidden="true" className="pointer-events-none absolute bottom-[118px] right-[120px] hidden h-[220px] w-[300px] lg:block xl:right-[200px]" style={{ perspective: '1800px' }}><div className="container-spin relative h-full w-full [transform-style:preserve-3d]">
    {[['translateZ(90px) rotateY(0deg)', 'FEEDBACK'], ['translateZ(-90px) rotateY(180deg)', 'MM SOFTWARES']].map(([transform, label]) => <div key={transform} className="absolute left-1/2 top-1/2 border border-verde-claro/60" style={{ ...longFace, backfaceVisibility: 'hidden', transform, backgroundColor: 'rgba(11,180,11,.09)', backgroundImage: 'repeating-linear-gradient(90deg, rgba(11,180,11,.38) 0 1px, transparent 1px 30.6px)' }}><span className="absolute inset-x-0 top-1.5 h-px bg-verde-claro/45" /><span className="absolute inset-x-0 bottom-1.5 h-px bg-verde-claro/45" /><span className="absolute left-5 top-1/2 -translate-y-1/2 font-titulo text-[11px] font-bold uppercase tracking-[0.3em] text-verde-claro">{label}</span></div>)}
    <div className="absolute left-1/2 top-1/2 flex border border-verde-claro/60" style={{ ...sideFace, backfaceVisibility: 'hidden', transform: 'rotateY(90deg) translateZ(223.2px)', backgroundColor: 'rgba(11,180,11,.09)' }}>{[0, 1].map(item => <div key={item} className="relative flex-1 border border-verde-claro/35"><span className="absolute inset-y-2 left-[32%] w-px bg-verde-claro/50" /><span className="absolute inset-y-2 left-[66%] w-px bg-verde-claro/50" /></div>)}</div>
    <div className="absolute left-1/2 top-1/2 border border-verde-claro/50" style={{ ...sideFace, backfaceVisibility: 'hidden', transform: 'rotateY(-90deg) translateZ(223.2px)', backgroundColor: 'rgba(11,180,11,.09)', backgroundImage: 'repeating-linear-gradient(90deg, rgba(11,180,11,.38) 0 1px, transparent 1px 30.6px)' }} />
    {['rotateX(90deg) translateZ(95.4px)', 'rotateX(-90deg) translateZ(95.4px)'].map(transform => <div key={transform} className="absolute left-1/2 top-1/2 border border-white/20" style={{ width: 446.4, height: 180, marginLeft: -223.2, marginTop: -90, backfaceVisibility: 'hidden', transform, backgroundColor: 'rgba(255,255,255,.05)', backgroundImage: 'repeating-linear-gradient(90deg, rgba(255,255,255,.16) 0 1px, transparent 1px 30.6px)' }} />)}
  </div></div>;
}

export default function Home() {
  const [company, setCompany] = useState('');
  const [token, setToken] = useState('');
  const [invitationState, setInvitationState] = useState('loading');
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('token') || ''; setToken(value); fetch('/api/convite?token=' + encodeURIComponent(value)).then(async r => { const data = await r.json() as { company: string; answered: boolean; message?: string }; if (!r.ok) throw new Error(data.message); setCompany(data.company); document.title = data.company + ' | Feedback MM Softwares'; setInvitationState(data.answered ? 'answered' : 'ready'); }).catch(e => setInvitationState(e.message)); }, []);
  const [activeForm, setActiveForm] = useState<FormKey>('treinamento');
  const [scrolled, setScrolled] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [sent, setSent] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const formRef = useRef<HTMLFormElement>(null);
  const selected = forms[activeForm];

  useEffect(() => { const update = () => setScrolled(window.scrollY > 40); update(); window.addEventListener('scroll', update, { passive: true }); return () => window.removeEventListener('scroll', update); }, []);
  const chooseForm = (key: FormKey) => { setActiveForm(key); setSent(false); setErrorMessage(''); setSubmitting(false); window.setTimeout(() => document.querySelector('#formulario')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 80); };
  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setSent(false); setErrorMessage(''); setSubmitting(true);
    try { const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch('/api/feedback', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...values, token }) }); const result = await response.json() as { message?: string }; if (!response.ok) throw new Error(result.message || 'Não foi possível enviar o feedback.'); setSent(true); setInvitationState('answered'); }
    catch (error) { setErrorMessage(error instanceof Error ? error.message : 'Não foi possível enviar o feedback.'); }
    finally { setSubmitting(false); }
  };

  if (invitationState !== 'ready') return <main className="min-h-screen bg-verde-escuro px-6 py-24 text-white"><div className="mx-auto max-w-xl"><img src="/mm-softwares-logo.webp" alt="MM Softwares" className="mb-12 h-16"/><h1 className="mb-5 text-3xl font-bold">{invitationState === 'loading' ? 'Carregando…' : invitationState === 'answered' ? 'Obrigado pelo seu feedback!' : 'Não foi possível abrir o formulário'}</h1><p role="status">{invitationState === 'answered' ? 'Sua resposta foi registrada e está disponível para a equipe responsável pelo acompanhamento.' : invitationState === 'loading' ? 'Estamos preparando sua página.' : invitationState}</p>{company && <p className="mt-6">{company}</p>}</div></main>;
  return <main className="min-h-screen overflow-x-hidden bg-fundo text-grafite">
    <nav className={`fixed inset-x-0 top-0 z-50 flex items-center justify-between gap-6 border-b border-white/15 px-6 transition-all duration-300 md:px-16 ${scrolled ? 'py-3 shadow-[0_4px_28px_rgba(6,26,24,.32)] md:py-4' : 'py-[18px] md:py-[30px]'}`}><div aria-hidden="true" className="absolute inset-0 bg-verde-escuro transition-opacity duration-300" style={{ opacity: Number(scrolled) }} /><a href="#topo" className="relative flex items-center" aria-label="MM Softwares - início"><img src="/mm-softwares-logo.webp" alt="MM Softwares" className={`w-auto transition-all duration-300 ${scrolled ? 'h-12' : 'h-16'}`} /></a><div className="relative hidden items-center gap-8 text-[15px] text-white/80 md:flex"><a href="#topo" className="transition-colors hover:text-verde-claro">Início</a><a href="#opcoes" className="transition-colors hover:text-verde-claro">Opções</a><a href="#formulario" className="transition-colors hover:text-verde-claro">Formulário</a><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2.5 whitespace-nowrap border border-white/45 px-5 py-[11px] font-semibold text-white transition-colors hover:border-verde-claro hover:text-verde-claro"><MessageCircle className="h-[18px] w-[18px]" />Responder</a></div><a href="#formulario" className="relative text-[13px] uppercase tracking-[0.12em] text-white/75 transition-colors hover:text-verde-claro md:hidden">Formulário</a></nav>

    <div className="bg-verde-escuro"><section id="topo" className="relative flex min-h-[min(92vh,880px)] flex-col overflow-hidden"><img src="/itajai-terminais.webp" alt="Vista aérea dos terminais portuários de Itajaí, Santa Catarina" className="absolute inset-0 h-full w-full object-cover" /><div className="pointer-events-none absolute inset-0 bg-gradiente-marca" /><div className="pointer-events-none absolute inset-0 opacity-[0.14] [background-image:repeating-linear-gradient(90deg,rgba(255,255,255,.5)_0_1px,transparent_1px_120px)]" /><div className="h-[100px] shrink-0 md:h-[124px]" /><div className="relative flex max-w-[1000px] flex-1 flex-col justify-center gap-[34px] px-6 py-16 md:px-16 md:py-20"><div className="flex items-center gap-3.5"><div className="h-0.5 w-11 bg-verde-claro" /><span className="font-titulo text-[13px] font-semibold uppercase tracking-[0.2em] text-verde-claro md:text-sm">{company} · Canal de feedback</span></div><h1 className="m-0 font-titulo text-[40px] font-extrabold uppercase leading-[0.99] tracking-[-0.03em] text-white text-balance md:text-[78px]">{company}, sua experiência ajuda a gente a evoluir</h1><p className="m-0 max-w-[660px] text-lg leading-[1.55] text-white/85 text-pretty md:text-[22px]">Conte como foi o treinamento ou compartilhe sua experiência com o SIWEB e/ou WMS. Sua opinião direciona as nossas melhorias.</p><div className="flex flex-col gap-4 sm:flex-row sm:flex-wrap"><a href="#opcoes" className="inline-flex items-center justify-center bg-verde px-[34px] py-[19px] text-[17px] font-semibold text-white transition-colors hover:bg-verde-claro">Enviar meu feedback</a><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center border border-white/40 px-[34px] py-[19px] text-[17px] font-semibold text-white transition-colors hover:border-verde-claro hover:text-verde-claro">Responder pelo WhatsApp</a></div></div><ContainerWireframe /></section>
    </div>

    <section id="opcoes" className="scroll-mt-24 bg-fundo px-6 py-20 md:px-16 md:py-[120px]"><div className="mx-auto flex max-w-[1360px] flex-col gap-12"><div className="flex max-w-[780px] flex-col gap-[18px]"><span className="font-titulo text-[13px] font-semibold uppercase tracking-[0.2em] text-verde">Escolha uma opção</span><h2 className="m-0 font-titulo text-4xl font-extrabold uppercase leading-[1.02] tracking-[-0.03em] text-grafite text-balance md:text-[56px]">Sobre o que você quer falar?</h2><p className="m-0 text-lg leading-[1.6] text-texto-suave text-pretty md:text-xl">Escolha o assunto e responda somente às perguntas relacionadas à sua experiência.</p></div>
      <div className="grid gap-4 md:grid-cols-2">{(Object.entries(forms) as [FormKey, (typeof forms)[FormKey]][]).map(([key, form]) => { const Icon = form.icon; const active = activeForm === key; return <button key={key} type="button" onClick={() => chooseForm(key)} aria-pressed={active} className={`group min-h-[230px] border p-7 text-left transition-all duration-300 md:p-9 ${active ? 'border-verde bg-verde-escuro text-white shadow-[0_18px_50px_rgba(12,46,43,.22)]' : 'border-borda-clara-2 bg-white text-grafite hover:-translate-y-1 hover:border-verde/60 hover:shadow-[0_14px_32px_rgba(12,46,43,.09)]'}`}><div className="flex items-start justify-between gap-5"><span className={`flex h-12 w-12 items-center justify-center ${active ? 'bg-verde-claro/15 text-verde-claro' : 'bg-verde/10 text-verde'}`}><Icon className="h-6 w-6" strokeWidth={1.8} /></span><ArrowRight className={`h-5 w-5 transition-transform duration-300 group-hover:translate-x-1 ${active ? 'text-verde-claro' : 'text-texto-suave-2'}`} /></div><p className={`mt-7 font-titulo text-xs font-semibold uppercase tracking-[0.2em] ${active ? 'text-verde-claro' : 'text-verde'}`}>{form.eyebrow}</p><h3 className="mt-2 font-titulo text-[28px] font-bold leading-[1.1] tracking-[-0.02em]">{form.title}</h3><p className={`mt-3 text-[17px] leading-[1.55] ${active ? 'text-white/65' : 'text-texto-suave'}`}>{form.description}</p></button>; })}</div>
      <div id="formulario" className="scroll-mt-28 border-l-2 border-verde bg-white shadow-[0_10px_40px_rgba(12,46,43,.07)]"><div key={activeForm} className="animar-surgir"><div className="border-b border-borda-clara px-6 py-6 md:px-10"><span className="font-titulo text-xs font-semibold uppercase tracking-[0.2em] text-verde">Formulário selecionado</span><h3 className="mt-2 font-titulo text-[28px] font-bold leading-[1.1] tracking-[-0.02em] text-grafite md:text-[34px]">{selected.title}</h3></div><form ref={formRef} onSubmit={handleSubmit} className="space-y-7 p-6 md:p-10"><input type="hidden" name="feedbackType" value={activeForm} /><div className="grid gap-5 sm:grid-cols-2"><Field label="Nome" name="name" required /><label className="block"><span className="mb-2 block text-sm font-semibold">Empresa</span><input className="h-[52px] w-full border border-borda-clara-2 bg-fundo px-4" name="company" value={company} readOnly /></label></div>
        {activeForm === 'treinamento' ? <><Field label="Como está sua experiência inicial com a MM Softwares? Quais pontos positivos você destacaria até este momento?" name="initialExperience" paragraph required /><Field label="Os treinamentos estão atendendo às suas expectativas? Sua equipe está conseguindo acompanhar os conteúdos apresentados?" name="trainingExpectations" paragraph required /><Field label="Existe alguma dificuldade para acessar ou utilizar as ferramentas, ou alguma dúvida ou preocupação em que possamos ajudar?" name="difficulties" paragraph /><Field label="O que poderíamos fazer para tornar sua experiência ainda melhor?" name="improvements" paragraph /><Field label="Em uma palavra, como você definiria sua experiência até este momento?" name="experienceWord" /><Field label="Gostaria de deixar alguma mensagem para a equipe MM Softwares?" name="teamMessage" paragraph /></> : <><Field label="Como tem sido sua experiência com o SIWEB e/ou WMS até o momento? Conte-nos o que está funcionando bem e se existe alguma dificuldade ou ponto que poderia ser melhorado." name="productExperience" paragraph required /><fieldset><legend className="mb-3 font-titulo text-sm font-semibold text-grafite">De 1 a 5, qual nota você atribui à sua experiência geral com o SIWEB e/ou WMS?<span className="ml-1 text-verde">*</span></legend><div className="grid max-w-xl grid-cols-5 gap-2">{[1,2,3,4,5].map(note => <label key={note} className="cursor-pointer"><input className="peer sr-only" type="radio" name="rating" value={note} required /><span className="grid h-[52px] place-items-center border border-borda-clara-2 bg-white font-titulo font-bold text-grafite transition-all duration-300 peer-checked:border-verde peer-checked:bg-verde peer-checked:text-white peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-verde">{note}</span></label>)}</div><div className="mt-2 flex max-w-xl justify-between text-xs text-texto-suave-2"><span>Muito insatisfeito</span><span>Muito satisfeito</span></div></fieldset></>}
        {sent && <div role="status" className="animar-surgir flex items-start gap-3 border border-verde/40 bg-verde/10 p-4 text-sm text-grafite"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-verde" /><p><strong>Feedback enviado!</strong><br />Obrigado por ajudar a MM Softwares a evoluir.</p></div>}{errorMessage && <div role="alert" className="border border-red-300 bg-red-50 p-4 text-sm font-semibold text-red-800">{errorMessage}</div>}<button type="submit" disabled={submitting} className="inline-flex min-h-[58px] items-center justify-center gap-2.5 bg-verde px-9 text-[17px] font-semibold text-white transition-colors hover:bg-verde-claro disabled:cursor-wait disabled:opacity-60"><Send className="h-5 w-5" />{submitting ? 'Enviando…' : 'Enviar feedback'}</button></form></div></div>
    </div></section>

    <footer className="bg-grafite px-6 pb-12 pt-16 text-white md:px-16 md:pt-20"><div className="mx-auto flex max-w-[1360px] flex-col gap-12"><div className="grid grid-cols-1 gap-9 md:grid-cols-[1.2fr_1.3fr_0.7fr] md:gap-12"><div className="flex flex-col gap-4"><img src="/mm-softwares-logo.webp" alt="MM Softwares" className="h-16 w-auto self-start" /><p className="max-w-[340px] text-base leading-[1.6] text-white/60">Tecnologia que conecta operação, controle e resultado.</p></div><div className="flex flex-col gap-3.5"><span className="font-titulo text-xs font-semibold uppercase tracking-[0.2em] text-verde-claro">Contato</span><span className="text-base leading-[1.55] text-white/75">Rua Cônego Tomás Fontes, 133 - Centro<br />Itajaí - SC, 88301-100</span><a href="mailto:atendimento@mmsoftwares.com.br" className="text-base text-white/75 transition-colors hover:text-verde-claro">atendimento@mmsoftwares.com.br</a></div><div className="flex flex-col gap-3.5"><span className="font-titulo text-xs font-semibold uppercase tracking-[0.2em] text-verde-claro">Redes</span><a href="https://www.instagram.com/mmsoftwares/" target="_blank" rel="noreferrer" className="text-base text-white/75 transition-colors hover:text-verde-claro">Instagram</a><a href="https://www.linkedin.com/company/mmsoftwares" target="_blank" rel="noreferrer" className="text-base text-white/75 transition-colors hover:text-verde-claro">LinkedIn</a></div></div><div className="flex flex-wrap items-center justify-between gap-6 border-t border-white/15 pt-7"><span className="text-[15px] text-white/45">© 2026 MM Softwares. Todos os direitos reservados.</span><a href="https://www.mmsoftwares.com.br/" target="_blank" rel="noreferrer" className="text-[15px] text-white/60 transition-colors hover:text-verde-claro">Site oficial</a></div></div></footer>
    <a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" aria-label="Responder pelo WhatsApp" className="fixed bottom-6 right-6 z-50 inline-flex items-center gap-2.5 bg-verde px-[22px] py-4 text-base font-semibold text-white shadow-[0_12px_30px_rgba(12,46,43,.35)] transition-colors hover:bg-verde-claro"><MessageCircle className="h-6 w-6" /><span className="hidden sm:inline">Responder pelo WhatsApp</span></a>
  </main>;
}
